#!/usr/bin/env php
<?php

use Tivins\Core\System\FileSys;

require "vendor/autoload.php";

$publicDir = 'front';

var_dump([
    'argv' => $argv,
    'dir' => __dir__,
    'cwd' => getcwd(),
]);

$cwd = getcwd();
FileSys::copy(__dir__ . '/template/front/main.js', $cwd . '/'.$publicDir.'/main.js');